recipe: default.v1

assistant_id: neero_assistant

language: fr

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    entity_recognition: true
    ranking_length: 5
  - name: EntitySynonymMapper
  - name: ResponseSelector
    retrieval_intent: chitchat
    epochs: 100
    constrain_similarities: true
    scale_loss: false
  - name: FallbackClassifier
    threshold: 0.5
    ambiguity_threshold: 0.1

policies:
  - name: AugmentedMemoizationPolicy
    max_history: 6
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: utter_default
    enable_fallback_prediction: true
  - name: TEDPolicy
    max_history: 6
    epochs: 100
    constrain_similarities: true
